# Generated by Django 5.1.4 on 2025-01-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user_phone_number_alter_assignment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="preferred_language",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred language for notifications",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.language",
            ),
        ),
    ]
