# Generated by Django 5.1.4 on 2025-01-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_notificationpreference_preferred_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="interpreter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.interpreter",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "interpreter", "start_time"],
                name="app_assignm_status_986cf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["created_at"], name="app_assignm_created_0229b7_idx"
            ),
        ),
        migrations.AddField(
            model_name="assignmentnotification",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="app.assignment",
            ),
        ),
        migrations.AddField(
            model_name="assignmentnotification",
            name="interpreter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_notifications",
                to="app.interpreter",
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentnotification",
            index=models.Index(
                fields=["interpreter", "is_read"], name="app_assignm_interpr_0de326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentnotification",
            index=models.Index(
                fields=["created_at"], name="app_assignm_created_6849c4_idx"
            ),
        ),
    ]
