# Generated by Django 5.1.4 on 2025-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_assignmentnotification_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpreter",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="interpreter",
            name="routing_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
